#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible
sudo apt-get upgrade -y
## Pull Ansible Config 
# sudo ansible-pull -U https://github.com/jmpTeixeira02/autodeploy
ansible-playbook local.yml
