#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## Pull Ansible Config 
sudo ansible-pull -U https://github.com/jmpTeixeira02/local.yml
