- hosts: localhost
  become: no
  pre_tasks:
    - name: Update Apt
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      become: true
  vars_prompt:
    - name: password
      prompt: Provide sudo password
  tasks:
    - name: Ansible Deps
      ansible.builtin.import_tasks:
        file: tasks/deps.yml
    - name: ZSH Setup
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml
      tags:
        - zsh
    - name: Core Libraries
      ansible.builtin.import_tasks:
        file: tasks/core.yml
      tags:
        - core
      become: true
    - name: NVIM Setup
      ansible.builtin.import_tasks:
        file: tasks/nvim.yml
      tags:
        - nvim
    - name: DotFiles Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/dotfiles.yml
      tags:
        - dotfiles
    - name: TMUX
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      tags:
        - tmux
    - name: Work
      ansible.builtin.import_tasks:
        file: tasks/work.yml
      tags:
        - work 
