- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - core
  tasks:
    - name: ZSH Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml
        apply:
          tags:
            - core
            - zsh
    - name: Core Libraries
      ansible.builtin.import_tasks:
        file: tasks/core.yml
        apply:
          tags:
            - core
    - name: NVIM Setup Tasls
      ansible.builtin.import_tasks:
        file: tasks/nvim.yml
        apply:
          tags:
            - core
            - nvim
    - name: DotFiles Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/dotfiles.yml
        apply:
          tags:
            - core
    - name: TMUX Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
        apply:
          tags:
            - core
            - tmux 
