- hosts: localhost
  become: no 
  pre_tasks:
    - name: Update Apt
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      become: true
  tasks:
    - name: ZSH Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml
      tags:
        - zsh
    - name: Core Libraries
      ansible.builtin.import_tasks:
        file: tasks/core.yml
    - name: NVIM Setup Tasls
      ansible.builtin.import_tasks:
        file: tasks/nvim.yml
      tags:
        - nvim
    - name: DotFiles Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/dotfiles.yml
      tags:
        - dotfiles
    - name: TMUX Setup Tasks
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      tags:
        - tmux 
