#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run with sudo. Exiting..."
    exit 1
fi

apt-get update
# Install Docker if sandbox
if [ "$1" = "sandbox" ]
then 
    apt-get install ca-certificates curl -y
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update   
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    usermod -aG docker $USER
    newgrp docker
fi

# Install Ansible
apt-get install ansible -y
