- name: Install Make
  apt: name=make
- name: Install GCC 
  apt: name=gcc
- name: Install GVM
  shell: curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
- name: Install Go 
  shell: gvm install go
- name: Instal lazygit
  shell: go install github.com/jesseduffield/lazygit@latest
- name: Install fd 
  apt: name=fd-find
- name: Install fzf
  apt: name=fzf
- name: FZF Alias
  shell: ln -s $(which fdfind) ~/.local/bin/fd
- name: Install bat preview
  apt: name=bat
- name: Bat Alias
  shell: |
    mkdir -p ~/.local/bin
    ln -s /usr/bin/batcat ~/.local/bin/bat
- name: Install unzip
  apt: name=unzip
- name: Install nvm
  apt: name=nvm
- name: Install node
  shell: nvm install 20
