- name: Install Make
  apt: name=make
- name: Install Bison 
  apt: name=bison
- name: Install GCC 
  apt: name=gcc
- name: Install GVM
  shell: curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
  ignore_errors: true
- name: Install Go 
  shell: |
    source ~/.gvm/scripts/gvm
    gvm install go1.23
  args:
    executable: /bin/bash
- name: Instal lazygit
  shell: go install github.com/jesseduffield/lazygit@latest
- name: Install fd 
  apt: name=fd-find
- name: FD Alias
  shell: |
    mkdir -p ~/.local/bin
    ln -s $(which fdfind) ~/.local/bin/fd
- name: Install fzf
  apt: name=fzf
- name: Install bat preview
  apt: name=bat
- name: Install unzip
  apt: name=unzip
- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
- name: Install npm 
  apt: name=npm
- name: Install node
  become_user: root
  shell: |
    source ~/.nvm/nvm.sh
    nvm install 20
  args:
    executable: /bin/bash
