- name: Install GCC 
  apt: name=gcc
  become: true
- name: Install GH 
  apt: name=gh
  become: true
- name: Get Rust, btw
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  changed_when: false
