- name: Install GCC 
  apt: name=gcc
- name: Install GVM
  shell: curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
- name: Install Go 
  shell: gvm install go
- name: Instal lazygit
  shell: go install github.com/jesseduffield/lazygit@latest
- name: Install fd 
  apt: name=fd-find
- name: Install unzip
  apt: name=unzip
- name: Install nvm
  apt: name=nvm
