- name: Install ZSH
  apt: name=zsh
  become: true
- name: Change Shell to ZSH
  expect:
    command: chsh -s /usr/bin/zsh
    responses:
      "Password:": "{{password}}"
  become: false
- name: Check that the oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
- name: Install ohmyzsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  when: oh_my_stats.stat.exists == False
- name: Install ZSH Autosugest
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
- name: Install ZSH Highlights
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: '~/.oh-my-zsh/plugins/zsh-syntax-highlighting'
- name: Install ZSH AutoComplete
  ansible.builtin.git:
    repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
    dest: '~/.oh-my-zsh/plugins/zsh-autocomplete'
- name: Download ZSH Starship Theme
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  become: true
- name: Install ZSH Starhship Theme
  become: true
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh
